---
title: "Data Visualization"
author: "Amritpal Sandhu"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)

library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

library(gapminder)

# library(sf)
```

```{r}
lizards <- read_csv(here::here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards) + geom_point(aes(x = total_length, y = weight))
```

```{r}
# Create a histogram of total lengths for all lizards in the dataset.

# Put variables inside of aes not things that refer to constants 

plot_1 <- ggplot(data = lizards, aes(x = total_length)) + 
  geom_histogram(color = "orange",
                 fill = "purple",
                 size = .3,
                 linetype = "dotted")

plot_1
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(shape = 22, 
             color = "cyan4",
             fill = "yellow",
             size = 4,
             alpha = .4)
```

```{r}
ggplot(data = lizards, aes(x = total_length, 
                           y = weight)) + 
  geom_point(aes(color = common_name, 
                 size = total_length),
             alpha = 0.5) +
  theme_minimal()
```

# Faceting and ~ means a function of

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, scales = "free")
```

# Re-ordering

```{r}
lizard_count <- lizards |>
  group_by(common_name) |>
summarize(
  counts = n()
)
 # OR

lizard_count_2 <- lizards |>
  count(common_name, site, tail)
```

```{r}
## Make column graph

ggplot(data = lizard_count_2, 
       aes(y = fct_reorder(common_name, n),
                                x = n)) +
  geom_col()

## Factor(fct) to reorder things based on values
```

Create a scatterplot, faceted by species, for total length versus weight. The color and shape  of points should differ based on the species (common name). Change the theme. Make each faceted panel have flexible axis limits (scales should be free).

```{r}
ggplot(data = lizards, 
       aes(x = total_length,
           y = weight)) + 
  geom_point(aes(color = common_name,
                 shape = ,
                 alpha = 0.6,
                 size = 3)) +
  facet_wrap(~common_name, scales = "free") + theme_light() + 
  labs(x = "Total Length (mm)",
       y = "Weight (grams)", 
       title = "Lizard sizes", 
       subtitle = "All lizards follow the standard length-weight relationship",
       caption = "Data : Jordana ...")
  
```

